// <auto-generated />
using BlazorContactsApi;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlazorContactsApi.Migrations
{
    [DbContext(typeof(ContactsContext))]
    [Migration("20210409032107_Seed Data")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Shared.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("State")
                        .HasColumnType("char(2)");

                    b.Property<string>("Zip")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Test St",
                            City = "Overland Park",
                            Name = "Carol Mason",
                            State = "KS",
                            Zip = "66202"
                        },
                        new
                        {
                            Id = 2,
                            Address = "234 MyStreet",
                            City = "Overland Park",
                            Name = "Amy Montoni",
                            State = "KS",
                            Zip = "66207"
                        },
                        new
                        {
                            Id = 3,
                            Address = "123 Way",
                            City = "Overland Park",
                            Name = "Robert Morris",
                            State = "KS",
                            Zip = "66207"
                        },
                        new
                        {
                            Id = 4,
                            Address = "123 Example St",
                            City = "Overland Park",
                            Name = "Richard Thurmond",
                            State = "KS",
                            Zip = "66202"
                        },
                        new
                        {
                            Id = 5,
                            Address = "110 Example St",
                            City = "Overland Park",
                            Name = "Michelle Williams",
                            State = "KS",
                            Zip = "66202"
                        },
                        new
                        {
                            Id = 6,
                            Address = "123 Second",
                            City = "Overland Park",
                            Name = "Herbert White",
                            State = "KS",
                            Zip = "66207"
                        },
                        new
                        {
                            Id = 7,
                            Address = "234 First",
                            City = "Overland Park",
                            Name = "Rick Thames",
                            State = "KS",
                            Zip = "66202"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
